FROM docker.io/library/mysql:8.0

COPY my.cnf /etc/mysql/my.cnf

# how to build:
# cd ragpon
# cd /home/user/ragpon/ragpon/apps/mysql/mysql
# podman build -t ragpon-mysql:latest .

# how to run:
# see how_to_run_memo.txt

